# Generated by Django 4.0.5 on 2022-07-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(blank=True, default=1000000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('RUB', 'Rubles')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(db_index=False, default=''),
        ),
    ]
