# Generated by Django 4.0.5 on 2022-07-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_email',
        ),
    ]
